---
# Source: promstack/charts/kube-prometheus-stack/templates/prometheus-operator/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: promstack-operator
  labels:
    
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: promstack
    app.kubernetes.io/version: "62.3.1"
    app.kubernetes.io/part-of: promstack
    chart: kube-prometheus-stack-62.3.1
    release: "promstack"
    heritage: "Helm"
    app: promstack-operator
    app.kubernetes.io/name: promstack-prometheus-operator
    app.kubernetes.io/component: prometheus-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: promstack-operator
subjects:
- kind: ServiceAccount
  name: promstack-operator
  namespace: monitoring
