---
# Source: promstack/charts/kube-prometheus-stack/templates/prometheus-operator/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: promstack-operator
  namespace: monitoring
  labels:
    
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: promstack
    app.kubernetes.io/version: "62.3.1"
    app.kubernetes.io/part-of: promstack
    chart: kube-prometheus-stack-62.3.1
    release: "promstack"
    heritage: "Helm"
    app: promstack-operator
    app.kubernetes.io/name: promstack-prometheus-operator
    app.kubernetes.io/component: prometheus-operator
spec:
  
  endpoints:
  - port: https
    scheme: https
    tlsConfig:
      serverName: promstack-operator
      ca:
        secret:
          name: promstack-admission
          key: ca
          optional: false
    honorLabels: true
    metricRelabelings:
      - action: drop
        regex: prometheus_operator_(kubernetes_client|reconcile_duration).*
        sourceLabels:
        - __name__
      - action: drop
        regex: go_sched_.*_bucket
        sourceLabels:
        - __name__
  selector:
    matchLabels:
      app: promstack-operator
      release: "promstack"
  namespaceSelector:
    matchNames:
      - "monitoring"
