---
# Source: forgejo/charts/postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: forgejo-postgresql
  namespace: "forgejo"
  labels:
    app.kubernetes.io/instance: forgejo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 16.4.0
    helm.sh/chart: postgresql-15.5.38
type: Opaque
data:
  postgres-password: "U1hIcjdJUFYzMA=="
  password: "Z2l0ZWE="
  # We don't auto-generate LDAP password when it's not provided as we do for other passwords
