---
# Source: renovate/charts/renovate/templates/config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-forgejo-config
  labels:
    helm.sh/chart: renovate-38.119.0
    app.kubernetes.io/name: renovate
    app.kubernetes.io/instance: renovate
    app.kubernetes.io/version: "38.119.0"
    app.kubernetes.io/managed-by: Helm
data:
  config.json: |-
    {
       "platform": "gitea",
       "autodiscover": false,
       "extends": [
         ":semanticCommitsDisabled"
       ],
       "username": "clux",
       "gitAuthor": "sszynrae <noreply@clux.dev>",
       "automerge": true,
       "automergeStrategy": "squash",
       "allowedPostUpgradeCommands": ["just"],
       "printConfig": true,
       "dependencyDashboard": false,
       "platformCommit": false,
       "repositories": [],
       "enabledManagers": ["helmv3", "custom.regex", "dockerfile", "cargo"],
       "packageRules": [{"matchManagers": ["helmv3"], "rangeStrategy": "pin"}],
       "customManagers": []
    }
