---
# Source: renovate/charts/renovate/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: renovate-forgejo-cache
  labels:
    helm.sh/chart: renovate-38.119.0
    app.kubernetes.io/name: renovate
    app.kubernetes.io/instance: renovate
    app.kubernetes.io/version: "38.119.0"
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
