---
# Source: promstack/charts/kube-prometheus-stack/charts/grafana/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: promstack-grafana
  namespace: monitoring
  labels:
    helm.sh/chart: grafana-8.4.9
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: promstack
    app.kubernetes.io/version: "11.1.5"
    app.kubernetes.io/managed-by: Helm
data:
  
  grafana.ini: |
    [alerting]
    enabled = false
    [analytics]
    check_for_updates = false
    [dashboards]
    default_home_dashboard_path = /tmp/dashboards/cx-home.json
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    domain = grafana.clux.dev
    [unified_alerting]
    enabled = false
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - defaultDatasourceScrapeInterval: 60s
      httpMethod: POST
      isDefault: true
      jsonData:
        exemplarTraceIdDestinations:
        - datasourceUid: Tempo
          name: trace_id
      name: Prometheus
      type: prometheus
      uid: Prometheus
      url: http://promstack-prometheus:9090/
    - name: Tempo
      type: tempo
      uid: Tempo
      url: http://promstack-tempo:3100/
