---
# Source: promstack/charts/kube-prometheus-stack/charts/grafana/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: promstack-grafana
  namespace: monitoring
  labels:
    helm.sh/chart: grafana-8.4.9
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: promstack
    app.kubernetes.io/version: "11.1.5"
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["configmaps", "secrets"]
    verbs: ["get", "watch", "list"]
