---
# Source: promstack/charts/kube-prometheus-stack/charts/grafana/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: promstack-grafana
  namespace: monitoring
  labels:
    helm.sh/chart: grafana-8.4.9
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: promstack
    app.kubernetes.io/version: "11.1.5"
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  
  admin-user: "YWRtaW4="
  admin-password: "cHJvbS1vcGVyYXRvcg=="
  ldap-toml: ""
