---
# Source: promstack/charts/kube-prometheus-stack/charts/grafana/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: promstack-grafana
  namespace: monitoring
  labels:
    helm.sh/chart: grafana-8.5.2
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: promstack
    app.kubernetes.io/version: "11.2.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - name: http-web
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: promstack
