apiVersion: v2
name: flux
description: wrapper over flux2
type: application
version: 0.1.0
dependencies:
- name: flux2
  version: "2.*"
  repository: https://fluxcd-community.github.io/helm-charts
  condition: flux2.enabled
