---
renovate:
  # templated config values
  repositories: [] #  must be json
  # https://github.com/renovatebot/helm-charts/blob/main/charts/renovate/values.yaml
  cronjob:
    #schedule: '0 1 * * *'  # At 01:00 every day
    schedule: "@daily"
    suspend: false
    concurrencyPolicy: 'Forbid'
    #completions: 1
    #completionMode: 'Indexed'
    failedJobsHistoryLimit: '5'
    successfulJobsHistoryLimit: ''
    jobRestartPolicy: Never
    ttlSecondsAfterFinished: '86400'
    activeDeadlineSeconds: '3600'
    jobBackoffLimit: '0'
    #parallelism: ''
    initContainers: []
    # Verify tooling
    # preCommand: |
    #   set -x
    #   rg --version && which rg
    #   fd --version && which fd
    #   just --version && which just
    #   sd --version && which sd
    #   yq --version && which yq
    #   protoc --version || which protoc
    #   cargo --version && which cargo
    #   rustc --version && which rustc
    #   cargo fmt --version && which rustfmt
  image:
    registry: ghcr.io
    tag: 37.440.7-slim3
    repository: clux/renovate

  securityContext:
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch

  # See https://docs.renovatebot.com/self-hosted-configuration
  renovate:
    config: |
      {
         "platform": "github",
         "autodiscover": false,
         "extends": [
           ":semanticCommitsDisabled"
         ],
         "username": "sszynrae",
         "gitAuthor": "Renovate <20075896+sszynrae@users.noreply.github.com>",
         "automerge": true,
         "automergeStrategy": "squash",
         "allowedPostUpgradeCommands": ["just"],
         "addLabels": ["dependencies"],
         "prFooter": "PR generated by [Renovate Bot](https://github.com/renovatebot/renovate) running in @clux's [homelab](https://github.com/clux/homelab).",
         "printConfig": true,
         "dependencyDashboard": false,
         "platformCommit": "disabled",
         "repositories": {{ .Values.repositories }},
         "enabledManagers": ["helmv3", "custom.regex", "dockerfile"],
         "packageRules": [{"matchManagers": ["helmv3"], "rangeStrategy": "pin"}],
         "customManagers": []
      }
    # Needs an override file on top of this to set repositories
    configEnableHelmTpl: true

    persistence:
      cache:
        enabled: true
        storageSize: "10Gi"

  ssh_config:
    enabled: true
    # format: https://github.com/renovatebot/helm-charts/blob/main/charts/renovate/templates/ssh-secret.yaml
    existingSecret: 'renovate-ssh'

  serviceAccount:
    create: false

  resources:
    limits:
      cpu: 4
      memory: 8Gi
    requests:
      memory: 1Gi

  # inject secrets from just secrets-renovate; done in overrides
  envFrom: []
  env:
    LOG_LEVEL: debug
    OTEL_EXPORTER_OTLP_ENDPOINT: http://promstack-tempo.monitoring.svc:4318
  envList: []

  redis:
    # https://github.com/bitnami/charts/tree/master/bitnami/redis
    enabled: false

  apiVersionOverrides:
    cronjob: 'batch/v1'

  # -- Environment variables that should be referenced from a k8s secret, cannot be used when existingSecret is set
  secrets: {}
  extraConfigmaps: []
  extraVolumes: []
  extraVolumeMounts: []
  extraContainers: []
