---
# Source: promstack/charts/kube-prometheus-stack/charts/kube-state-metrics/templates/crs-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: promstack-kube-state-metrics-customresourcestate-config
  namespace: monitoring
  labels:    
    helm.sh/chart: kube-state-metrics-5.25.1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: kube-state-metrics
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/instance: promstack
    app.kubernetes.io/version: "2.13.0"
    release: promstack
data:
  config.yaml: |
    spec:
      resources:
      - groupVersionKind:
          group: kustomize.toolkit.fluxcd.io
          kind: Kustomization
          version: v1
        metricNamePrefix: gotk2
        metrics:
        - each:
            info:
              labelsFromPath:
                name:
                - metadata
                - name
            type: Info
          help: The current state of a Flux Kustomization resource.
          labelsFromPath:
            ready:
            - status
            - conditions
            - '[type=Ready]'
            - status
            revision:
            - status
            - lastAppliedRevision
            source_name:
            - spec
            - sourceRef
            - name
            suspended:
            - spec
            - suspend
          name: resource_info
      - groupVersionKind:
          group: source.toolkit.fluxcd.io
          kind: GitRepository
          version: v1
        metricNamePrefix: gotk3
        metrics:
        - each:
            info:
              labelsFromPath:
                name:
                - metadata
                - name
            type: Info
          help: The current state of a Flux GitRepository resource.
          labelsFromPath:
            ready:
            - status
            - conditions
            - '[type=Ready]'
            - status
            revision:
            - status
            - artifact
            - revision
            suspended:
            - spec
            - suspend
            url:
            - spec
            - url
          name: resource_info
