---
# Source: flux/templates/monitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: flux
spec:
  namespaceSelector:
    matchNames:
      - flux
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - helm-controller
          - source-controller
          - kustomize-controller
          - notification-controller
          - image-automation-controller
          - image-reflector-controller
  podMetricsEndpoints:
    - port: http-prom
      relabelings:
      - action: keep
        regex: Running
        sourceLabels:
        - __meta_kubernetes_pod_phase
      metricRelabelings:
      - sourceLabels: [__name__]
        action: drop
        regex: '^go_.*'
      - sourceLabels: [__name__]
        action: drop
        regex: '.*_seconds_bucket'
