---
# Source: promstack/charts/kube-prometheus-stack/templates/prometheus/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: promstack-prometheus
  namespace: monitoring
  labels:
    app: promstack-prometheus
    app.kubernetes.io/name: promstack-prometheus
    app.kubernetes.io/component: prometheus
    
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: promstack
    app.kubernetes.io/version: "62.3.1"
    app.kubernetes.io/part-of: promstack
    chart: kube-prometheus-stack-62.3.1
    release: "promstack"
    heritage: "Helm"
automountServiceAccountToken: true
